export const ApiConfig = {
  basePathCommittee : ":8055/kla/service/v1/committee",
  basePathNotification: ':8066/kla/service/v1/notification',
  basePathCorrespondence: ':8066/kla/service/v1/correspondence',
  basePathReg: ':8089/kla/service/v1/departmentMangement',
  uploadFile: ':8088/file/uploadImage',
  basePathTable : ":8075/kla/service/v1/table",
  basePathTableV2 :":8075/kla/service/v2/table",
  basePathBudget : ":8008/kla/service/v1/budget",
  basePathBill: ':8044/kla/service/v1/bill',

  correspondenceTemplate: {
    getAllWorkFlow: '/template/workflow/type',
    getTypeBySection: '/getAll',
    getAllInputType: '/template/inputType/getAll',
    saveTemplateWithInputs: '/template/createTemplateWithInput',
    getAllBusiness: '/template/business/getAll',
    getTemplateById: '/template/getById',
    deleteTemplateInput: '/template/deleteTemplateInput',
    getAllTemplate: '/template/getAllTemplates',
    getPending: '/pending',
    sent: '/sent',
    inbox: '/inbox',
    outbox: '/outbox',
    addNote: '/notes',
    deleteNote: '/notes/byId',
    getAllCode: '/getAllCode',
    deleteTemplate: '/template/deleteTemplate',
  },
  notification: {
    getCurrespondenceDepartmentRecieved: '/letter/getCorresponseDepartmentRecived?departmentId',
    chnageUploadStatus: '/letter/markSent?correspondenceId',
    uploadDelayStatement: '/letter/sendDelayStatement',
  },
};
