
export const ApiConfig = {
  basePathExt: ":8008/kla/service/v1/budget",
  basePathFile: ":8078/kla/service/v1/files",
  basePathWorkflow: ":9000/kla/workflow/service/v1/task",
  basePathBulletinFile: ":8078/kla/service/v1/bulletin",
  basePathReg: ":8089/kla/service/v1/departmentMangement",
  basePathNotification: ":8066/kla/service/v1/notification",
  basePathCorrespondence: ":8066/kla/service/v1/correspondence",
  basePathBillFile:":8044/kla/service/v1/bill",
  budgetspeech: {
    speech: '/speech',
    save: "/speech/create",
    submit: "/speech/submit",
    list: "/speech/getAll",
    publishedlist: "/speech/getAllPublished",
    getById: "/speech",
    timeAllocation: {
      save: "/timeAllocation/save",
      submit: "/timeAllocation/submit",
      generate: "/timeAllocation/generateTimeAllocation",
      getDayAndDates: "/timeAllocation/getDayAndDates",
      getByFileIdAndDay: "/timeAllocation/getByFileIdAndDay",
      setToLOB: "/timeAllocation/uploadToLOB",
      getTimeByFileIdAndDay: "/timeAllocation/getMemberAllocation",
      getTimeAllocationMember: "/timeAllocation/getAllocationDetails"
    }
  },
  budget_main:{
    save:'/save',
    create :'/budget',
    list: "/document/getAll",
    
  },
  budegtdocument:{
    save:'/document/save',
    submit :'/document/submit',
    list: "/document/getAll",
    listapproved:"/document/approved",
    getById:"/document",
    validatePasswd: "/document/authenticateToAccessUrl",
    claim: "/workflow/claim",
    sdfg: {
      demands : {list: "/demand/getAll", changeOrdr:"/demand/changeOrder" },
      deleteSDFG: "/SDFG/delete",
      getAllSDFG: "/SDFG/getAllSDFG",
      published: "/SDFG/getPublishedSdfgs",
      approved: "/SDFG/getApprovedSdfgs",
      getById: "/SDFG/getById",
      getByLinesId: "/SDFG/getLines",
      saveSDFG: "/SDFG/save",
      saveAllSDFG: "/SDFG/saveAll",
      submitSDFG: "/SDFG/submit",
      publishSdfgs: "/SDFG/publish"
    },
  dds: {
    create: "/demand/draft/create",
    delete: "/demand/draft/delete",
    suggestionForOl: "/demand/draft/suggestionForOl",
    getById: "/demand/draft/getById",
    viewForAssistant: "/demand/draft/view/assisstant",
    getAll: "/demand/draft/getAll",
    getByIds: "/demand/draft/getByIds",
    submit: "/demand/draft/submit",
    approved: "/demand/draft/getApprovedDemandDrafts",
    getDemandHeads: "/demand/draft/getDemandHeads",
    getVersion:"/demand/draft/viewVersion",
    setApprovedVersion:"/demand/draft/setApprovedVersion",
    getDDSMaterids:"/demand/draft/getMasterData",
    getActiveNature: "/demand/draft/getActiveNature",
    getCosDatesForSdfgId: "/demand/draft/getCosDates",
    getDemandMasterById: "/demand/draft/getDemandMastersByDraftId",
    listOppo: "/demand/draft/getApprovedDemandDrafts/OL"
  },
  cutmotion: {
    create: "/sdfg/cutMotion/create",
    submit: "/sdfg/cutMotion/submit",
    delete: "/sdfg/cutMotion/delete",
    getAllForMembers: "/sdfg/cutMotion/getAllForMembers",
    getSdfgById: "/sdfg/cutMotion/getSdfgById",
    getAllSubmitted: "/sdfg/cutMotion/getAllSubmitted",
    getDemandsById:  "/sdfg/cutMotion/getDemandsById",
    getPublishedCutMotionsById: "/sdfg/cutMotion/getPublishedCutMotions",
    getApprovedCutMotionsById:  "/sdfg/cutMotion/getApprovedCutMotions",
    getApprovedCutMotionList:  "/sdfg/cutMotion/getApprovedList",
    getPublishedCutMotionList:  "/sdfg/cutMotion/getPublishedList",
    publishCutMotion: "/sdfg/cutMotion/publishCutMotion",
    resubmit: "/sdfg/cutMotion/resubmitCutMotion",
    isResubmit: "/sdfg/cutMotion/isResubmit",
    setToLOB: "/sdfg/cutMotion/setToLob",
    passCutMotion: "/sdfg/cutMotion/passCutMotion",
    listReport: "/sdfg/cutMotion/generateReport",
    bitlist:{
      createBitList: "/sdfg/bitList/create",
      getById: "/sdfg/bitList/getById",
      listToAddHeads: "/sdfg/bitList/listToAddHeads",
      submitBitList: "/sdfg/bitList/submit",
      getAll: "/sdfg/bitList/listForBitListPreparation",
      generateMr: "/sdfg/bitList/generateMinisterAndSpeakerReadingAndAttach",
      getPdfUrl: "/sdfg/bitList/getPdfUrl",
      revenueDetails: "/sdfg/bitList/revenueDetails",
      setToLob: "/sdfg/bitList/setToLob"
    }
  },
  greenbook: {
    create: "/greenBook/create",
    save: "/greenBook/save",
    getById: "/greenBook/getById"
  },
  grlRequest:
  {
    save:'/grl/save',
    submit :'/grl/submit',
    list: "/grl/getAll",
    getbudget:'/grlRequestReady',
  },

grlbullettin:{
  save:'/grlBulletin/save',
  submit :'/grlBulletin/submit',
  list: "/grlBulletin/getAll",

}
},
sdgEg:{
  save:'/sdgeg/save',
  submit :'/sdgeg/submit',
  list: "/sdgeg/getAll",
  getAllSdgEg:"/sdgAndeg/getAllSdgOrEg",
  saveSDGEG: "/sdgAndeg/save",
  saveAllSDGEG: "/sdgAndeg/saveAll",
  submitSDGEG: "/sdgAndeg/submit",
  getById: "/sdgAndeg/getById",
  receviedSDGEGinTS:"/sdgAndeg/received",
  receviedSDGEGinLS:"/sdgAndeg/receivedInLegislation",
  editGRLBulletin: "/sdgeg/letter/editGrlBulletin",
  addToLOB: "/sdgAndeg/addToLob/",
  sentToLS: "/sdgAndeg/sendToLegislation/" ,
  LSApproved: "/sdgAndeg/legislationApproved",
  publish:"/sdgAndeg/publish",
  publishedSdfg :'/sdgAndeg/published',
  setToLOB:'/sdgAndeg/setToLob/',
  dds: {
    create: "/demand/draft/sdgeg/create",
    submit: "/demand/draft/sdgeg/submit",
    getById: "/demand/draft/sdgeg/getById",
    getAll: "/demand/draft/sdgeg/getAll",
    approved: "/demand/draft/sdgeg/getApprovedDemandDrafts",
    suggestionForOl: "/demand/draft/sdgeg/suggestionForOl",
    getDDSMaterids:"/demand/draft/sdgeg/getMasterData",
    getVersion:"/demand/draft/sdgeg/viewVersion",
    setApprovedVersion:"/demand/draft/sdgeg/setApprovedVersion",
    getActiveNature: "/demand/draft/sdgeg/getActiveNature"
  }
},
appropriation: {
 getapprovedbills: "/appropriation/listValues/approved"
},
  correspondenceTemplate: {
    getAllWorkFlow: "/template/workflow/type",
    getTypeBySection: "/getAll",
    getAllInputType: "/template/inputType/getAll",
    saveTemplateWithInputs: "/template/createTemplateWithInput",
    getAllBusiness: "/template/business/getAll",
    getTemplateById: "/template/getById",
    deleteTemplateInput: "/template/deleteTemplateInput",
    getAllTemplate: "/template/getAllTemplates",
    getPending: "/pending",
    sent: "/sent",
    inbox: "/inbox",
    outbox: "/outbox",
    addNote: "/notes",
    deleteNote: "/notes/byId",
    getAllCode: "/getAllCode",
    deleteTemplate: "/template/deleteTemplate",
  },
  //old below - can be reused wherever required
  uploadFile: ":8088/file/uploadImage",
  portfolio: "mock/portfolio",
  department: "mock/subject",
  files: {
    create: "/file/createRegistrationList",
    list: "/all",
    approved: "/getAll",
    workFlowUsers: "/getWorkflowActionUsers",
    pendingFilesForUser: "/dashBoard/user",
    pendingFilesForSection: "/dashBoard/section",
    aaprovedByHigherOfficial: "/all/ownerId",
    changeSubmitStatus: "/document/submitDocument",
    addAttachment: "/addAttachment",
    statusUpdate: "/update/status",
    ratification: "/file/ratification/pending",
    getAll: "/file/getAll",
    getPending: "/file/getAllPending",
    speakerNote: '/file/getSpeakerNote',
    getFilebyId: "/file/getByFileId"
  },
  notification: {
  },
  notes: {
    create: "",
    list: "",
  },
  currespondenceTemplate: {
    getAllWorkFlow: "/template/workflow/type",
    getTypeBySection: "/getAll",
    getAllInputType: "/template/inputType/getAll",
    saveTemplateWithInputs: "/template/createTemplateWithInput",
    getAllBusiness: "/template/business/getAll",
    getTemplateById: "/template/getById",
    deleteTemplateInput: "/template/deleteTemplateInput",
    getAllTemplate: "/template/getAllTemplates",
    getPending: "/pending",
    sent: "/sent",
    inbox: "/inbox",
    outbox: "/outbox",
    addNote: "/notes",
    deleteNote: "/notes/byId",
    getAllCode: "/getAllCode",
    deleteTemplate: "/template/deleteTemplate",
  },
};
