export class CplDocs {

    constructor(
        public assembly: number = null,
        public assemblyId: number = null,
        public attachments: [{}] = [{}],
        public currentNumber: number = null,
        public fileId: number = null,
        public regFileNumber: any = null,
        public id: number = null,
        public gazettePublishDate: string = '',
        public goDate: string = '',
        public goNumber: number = null,
        public isDelayed: boolean = null,
        public ministerDepartmentId: number = null,
        public portfolioId: number = null,
        public sessionId: number = null,
        public typeDate: string = '',
        public docNumber: string = '',
        public typeNumber: string = '',
        public sroDate: string = '',
        public status: string = '',
        public title: string = '',
        public subType: string = '',
        public typeName: string = '',
        public type: string = '',
        public departmentFileNumber: any = null,
        public layingDate: any = null,
        public numberOfDaysInSabha: any = null,
        public layingProvisionInAct: any = null,
        public actType: any = null,
        public actName: any = null,
        public nameOfInstitution: any = null,
    ) {}
}
