
export const ApiConfig = {
  basePathExt: ':8044/kla/service/v1/bill',
  basePathFile: ':8078/kla/service/v1/files',
  basePathBulletinFile: ':8078/kla/service/v1/bulletin',
  basePathReg: ':8089/kla/service/v1/departmentMangement',
  basePathNotification: ':8066/kla/service/v1/notification',
  basePathCorrespondence: ':8066/kla/service/v1/correspondence',
  basePathCommittee: ':8055/kla/service/v1/committee',
  bill: {
    create: '/bill',
    viewById: '/bill/',
    list: '/bill/all',
    createBlock: '/block',
    createBlockType: 'block/type',
    createFile: '/file/createFile'
  },
  priorityList: {
    save: '/priorityList',
    delete: '/priorityList',
    submit: '/priorityList/submit',
    listAll: '/priorityList/all',
    submittedList: '/priorityList/submitted',
    getById: '/priorityList',
    categories: '/priorityList/category/all',
    listRequestAll: '/priorityList/request/list',
    submitPrioritylistRquest: '/priorityList/request',
    priorityListByAssemblySession: '/priorityList/by',
    sendPriorityListRequestResponse: '/priorityList/sendList',
    setInitialDays: '/priorityList/initial/dates',
    schedule: '/schedule',
    scheduleList: '',
    addCOS: '/priorityList/request/addCos'
  },
  billRegister: {
    addToRegister: '/',
    list: '',
    view: '',
  },
  bulletin: {
    create: '/bulletin',
    publish: '/publish',
    list: '/bulletin/list',
    approvedList: '/bulletin/list/approved',
    publishedList: '/bulletin/list/published',
    view: '/bulletin',
  },
  erratum: {
    request: '/',
    list: '',
    view: '',
  },
  // old below - can be reused wherever required
  uploadFile: ':8088/file/uploadImage',
  portfolio: 'mock/portfolio',
  department: 'mock/subject',
  files: {
    create: '/file/createRegistrationList',
    list: '/all',
    approved: '/getAll',
    workFlowUsers: '/getWorkflowActionUsers',
    pendingFilesForUser: '/dashBoard/user',
    pendingFilesForSection: '/dashBoard/section',
    aaprovedByHigherOfficial: '/all/ownerId',
    changeSubmitStatus: '/document/submitDocument',
    addAttachment: '/addAttachment',
    statusUpdate: '/update/status',
    ratification: '/file/ratification/pending',
    getAll: '/file/getAll',
    getPending: '/file/getAllPending',
    speakerNote: '/file/getSpeakerNote',
    getFilebyId: '/file/getByFileId'
  },
  notification: {
  },
  notes: {
    create: '',
    list: '',
  },
  currespondenceTemplate: {
    getAllWorkFlow: '/template/workflow/type',
    getTypeBySection: '/getAll',
    getAllInputType: '/template/inputType/getAll',
    saveTemplateWithInputs: '/template/createTemplateWithInput',
    getAllBusiness: '/template/business/getAll',
    getTemplateById: '/template/getById',
    deleteTemplateInput: '/template/deleteTemplateInput',
    getAllTemplate: '/template/getAllTemplates',
    getPending: '/pending',
    sent: '/sent',
    inbox: '/inbox',
    outbox: '/outbox',
    addNote: '/notes',
    deleteNote: '/notes/byId',
    getAllCode: '/getAllCode',
    deleteTemplate: '/template/deleteTemplate',
  },
};
