export const Response = {
    "latestList": {
      "id": "143ba538-ce42-4ac1-aaa9-e2347a84b3a5",
      "assemblyId": 1,
      "sessionId": 3,
      "fileId": 57,
      "fileNumber": "231/cpl -5/2020/ni.se",
      "allotmentDateId": 3,
      "layingDate": "2020-08-15",
      "status": "SUBMITTED",
      "currentVersion": 2,
      "documentsByPortfolioDtos": [
        {
          "portfolio": 8,
          "type": "REPORT",
          "minister": "Shri. Pinarayi Vijayan",
          "documentMetaDatas": [
            {
              "id": "3aab00f5-38f9-42a3-927a-d945044621b8",
              "regFileNumber": "222/cpl -5/2020/ni.se",
              "listFileNumber": "231/cpl -5/2020/ni.se",
              "type": "ORDINANCE",
              "portfolioId": 8,
              "goNumber": "124342",
              "goDate": "2020-05-18",
              "gazettePublishDate": "2020-05-02",
              "isDelayed": false,
              "status": "LAYING_APPROVED",
              "layingDate": null,
              "departmentFileNumber": "string",
              "numberOfDaysInSabha": 22,
              "layingProvisionInAct": "Minister for Welfare of Scheduled Castes, Scheduled Tribes and Backward Classes ,Law, Cultur",
              "title": "ORDINANCE 6",
              "typeName": "asdf",
              "actType": "STATE",
              "actName": "act NAME",
              "typeNumber": "asdf",
              "typeDate": "2020-05-02",
              "typeYear": "2020-2021",
              "sectionName": "",
              "subType": "NO_SUBTYPE",
              "ministerDepartmentName": "General Administration",
              "createdDate": "2020-05-27T19:20:43.068+0000"
            },
            {
              "id": "b821fd3b-8878-4bac-90f1-181a0feac34a",
              "regFileNumber": "222/cpl -5/2020/ni.se",
              "listFileNumber": "231/cpl -5/2020/ni.se",
              "type": "SRO",
              "portfolioId": 8,
              "goNumber": "124342",
              "goDate": "2020-05-18",
              "gazettePublishDate": "2020-05-02",
              "isDelayed": false,
              "status": "LAYING_APPROVED",
              "layingDate": null,
              "departmentFileNumber": "string",
              "numberOfDaysInSabha": 22,
              "layingProvisionInAct": "Minister for Welfare of Scheduled Castes, Scheduled Tribes and Backward Classes ,Law, Cultur",
              "title": "ORDINANCE 5",
              "typeName": "asdf",
              "actType": "STATE",
              "actName": "act NAME",
              "typeNumber": "asdf",
              "typeDate": "2020-05-02",
              "typeYear": "2020-2021",
              "sectionName": "",
              "subType": "NO_SUBTYPE",
              "ministerDepartmentName": "General Administration",
              "createdDate": "2020-05-27T19:20:44.981+0000"
            }
          ],
          "portfolioName": "Chief Minister"
        },
        {
          "portfolio": 11,
          "type": "ORDINANCE",
          "minister": " Dr.K.T.Jaleel",
          "documentMetaDatas": [
            {
              "id": "e5e7f4bc-9fc8-4806-80b4-f5d98f8ef839",
              "regFileNumber": "223/cpl -5/2020/ni.se",
              "listFileNumber": "231/cpl -5/2020/ni.se",
              "type": "ORDINANCE",
              "portfolioId": 11,
              "goNumber": "124342",
              "goDate": "2020-05-18",
              "gazettePublishDate": "2020-05-02",
              "isDelayed": false,
              "status": "LAYING_APPROVED",
              "layingDate": null,
              "departmentFileNumber": "string",
              "numberOfDaysInSabha": 22,
              "layingProvisionInAct": "Minister for Welfare of Scheduled Castes, Scheduled Tribes and Backward Classes ,Law, Cultur",
              "title": "ORDINANCE 4",
              "typeName": "asdf",
              "actType": "STATE",
              "actName": "act NAME",
              "typeNumber": "asdf",
              "typeDate": "2020-05-02",
              "typeYear": "2020-2021",
              "sectionName": "",
              "subType": "NO_SUBTYPE",
              "ministerDepartmentName": "Collegiate Education",
              "createdDate": "2020-05-27T19:20:46.811+0000"
            },
            {
              "id": "8d63040e-b1d2-493c-a278-b4dfba972a7e",
              "regFileNumber": "223/cpl -5/2020/ni.se",
              "listFileNumber": "231/cpl -5/2020/ni.se",
              "type": "ORDINANCE",
              "portfolioId": 11,
              "goNumber": "124342",
              "goDate": "2020-05-18",
              "gazettePublishDate": "2020-05-02",
              "isDelayed": false,
              "status": "LAYING_APPROVED",
              "layingDate": null,
              "departmentFileNumber": "string",
              "numberOfDaysInSabha": 22,
              "layingProvisionInAct": "Minister for Welfare of Scheduled Castes, Scheduled Tribes and Backward Classes ,Law, Cultur",
              "title": "ORDINANCE 3",
              "typeName": "asdf",
              "actType": "STATE",
              "actName": "act NAME",
              "typeNumber": "asdf",
              "typeDate": "2020-05-02",
              "typeYear": "2020-2021",
              "sectionName": "",
              "subType": "NO_SUBTYPE",
              "ministerDepartmentName": "Technical Education",
              "createdDate": "2020-05-27T19:20:48.782+0000"
            }
          ],
          "portfolioName": "Minister for Higher Education and Minority Welfare"
        },
        {
          "portfolio": 12,
          "type": "ORDINANCE",
          "minister": "Shri  E. P. Jayarajan",
          "documentMetaDatas": [
            {
              "id": "7f02efe1-23c1-4c03-a2dc-ddb92ddfcaa8",
              "regFileNumber": "224/cpl -5/2020/ni.se",
              "listFileNumber": "231/cpl -5/2020/ni.se",
              "type": "ORDINANCE",
              "portfolioId": 12,
              "goNumber": "124342",
              "goDate": "2020-05-18",
              "gazettePublishDate": "2020-05-02",
              "isDelayed": false,
              "status": "LAYING_APPROVED",
              "layingDate": null,
              "departmentFileNumber": "string",
              "numberOfDaysInSabha": 22,
              "layingProvisionInAct": "Minister for Welfare of Scheduled Castes, Scheduled Tribes and Backward Classes ,Law, Cultur",
              "title": "ORDINANCE 2",
              "typeName": "asdf",
              "actType": "STATE",
              "actName": "act NAME",
              "typeNumber": "asdf",
              "typeDate": "2020-05-02",
              "typeYear": "2020-2021",
              "sectionName": "",
              "subType": "NO_SUBTYPE",
              "ministerDepartmentName": "Handlooms & Textiles",
              "createdDate": "2020-05-27T19:20:51.249+0000"
            },
            {
              "id": "a53e602f-2ecf-4d10-a14c-4aeffc33ed35",
              "regFileNumber": "224/cpl -5/2020/ni.se",
              "listFileNumber": "231/cpl -5/2020/ni.se",
              "type": "ORDINANCE",
              "portfolioId": 12,
              "goNumber": "124342",
              "goDate": "2020-05-18",
              "gazettePublishDate": "2020-05-02",
              "isDelayed": false,
              "status": "LAYING_APPROVED",
              "layingDate": null,
              "departmentFileNumber": "string",
              "numberOfDaysInSabha": 22,
              "layingProvisionInAct": "Minister for Welfare of Scheduled Castes, Scheduled Tribes and Backward Classes ,Law, Cultur",
              "title": "ORDINANCE 1",
              "typeName": "asdf",
              "actType": "STATE",
              "actName": "act NAME",
              "typeNumber": "asdf",
              "typeDate": "2020-05-02",
              "typeYear": "2020-2021",
              "sectionName": "",
              "subType": "NO_SUBTYPE",
              "ministerDepartmentName": "Industries (including Industrial Co-operatives) Commerce",
              "createdDate": "2020-05-27T19:20:53.548+0000"
            }
          ],
          "portfolioName": "Minister for Industries, Commerce, Sports and Youth Affairs"
        }
      ]
    },
    "versionMap": {
      "1": {
        "id": "143ba538-ce42-4ac1-aaa9-e2347a84b3a5",
        "assemblyId": 1,
        "sessionId": 2,
        "fileId": null,
        "fileNumber": null,
        "allotmentDateId": null,
        "layingDate": "2020-08-15",
        "status": "SAVED",
        "currentVersion": null,
        "documentsByPortfolioDtos": [
          {
            "portfolio": 8,
            "type": "ORDINANCE",
            "minister": "Shri. Pinarayi Vijayan",
            "documentMetaDatas": [
              {
                "id": "3aab00f5-38f9-42a3-927a-d945044621b8",
                "regFileNumber": "222/cpl -5/2020/ni.se",
                "listFileNumber": "string",
                "type": "ORDINANCE",
                "portfolioId": 8,
                "goNumber": "124342",
                "goDate": "2020-05-17T18:30:00.000+0000",
                "gazettePublishDate": "2020-05-01T18:30:00.000+0000",
                "isDelayed": false,
                "status": "LAYING_APPROVED",
                "layingDate": null,
                "departmentFileNumber": "string",
                "numberOfDaysInSabha": 22,
                "layingProvisionInAct": "Minister for Welfare of Scheduled Castes, Scheduled Tribes and Backward Classes ,Law, Cultur",
                "title": "ORDINANCE 6",
                "typeName": "asdf",
                "actType": "STATE",
                "actName": "act NAME",
                "typeNumber": "asdf",
                "typeDate": "2020-05-01T18:30:00.000+0000",
                "typeYear": "2020-2021",
                "sectionName": "",
                "subType": "NO_SUBTYPE",
                "ministerDepartmentName": "General Administration",
                "createdDate": "2020-05-27T19:20:43.068+0000"
              },
              {
                "id": "b821fd3b-8878-4bac-90f1-181a0feac34a",
                "regFileNumber": "222/cpl -5/2020/ni.se",
                "listFileNumber": "string",
                "type": "ORDINANCE",
                "portfolioId": 8,
                "goNumber": "124342",
                "goDate": "2020-05-17T18:30:00.000+0000",
                "gazettePublishDate": "2020-05-01T18:30:00.000+0000",
                "isDelayed": false,
                "status": "LAYING_APPROVED",
                "layingDate": null,
                "departmentFileNumber": "string",
                "numberOfDaysInSabha": 22,
                "layingProvisionInAct": "Minister for Welfare of Scheduled Castes, Scheduled Tribes and Backward Classes ,Law, Cultur",
                "title": "ORDINANCE 5",
                "typeName": "asdf",
                "actType": "STATE",
                "actName": "act NAME",
                "typeNumber": "asdf",
                "typeDate": "2020-05-01T18:30:00.000+0000",
                "typeYear": "2020-2021",
                "sectionName": "",
                "subType": "NO_SUBTYPE",
                "ministerDepartmentName": "General Administration",
                "createdDate": "2020-05-27T19:20:44.981+0000"
              }
            ],
            "portfolioName": "Chief Minister"
          },
          {
            "portfolio": 12,
            "type": "ORDINANCE",
            "minister": "Shri  E. P. Jayarajan",
            "documentMetaDatas": [
              {
                "id": "7f02efe1-23c1-4c03-a2dc-ddb92ddfcaa8",
                "regFileNumber": "224/cpl -5/2020/ni.se",
                "listFileNumber": "string",
                "type": "ORDINANCE",
                "portfolioId": 12,
                "goNumber": "124342",
                "goDate": "2020-05-17T18:30:00.000+0000",
                "gazettePublishDate": "2020-05-01T18:30:00.000+0000",
                "isDelayed": false,
                "status": "LAYING_APPROVED",
                "layingDate": null,
                "departmentFileNumber": "string",
                "numberOfDaysInSabha": 22,
                "layingProvisionInAct": "Minister for Welfare of Scheduled Castes, Scheduled Tribes and Backward Classes ,Law, Cultur",
                "title": "ORDINANCE 2",
                "typeName": "asdf",
                "actType": "STATE",
                "actName": "act NAME",
                "typeNumber": "asdf",
                "typeDate": "2020-05-01T18:30:00.000+0000",
                "typeYear": "2020-2021",
                "sectionName": "",
                "subType": "NO_SUBTYPE",
                "ministerDepartmentName": "Handlooms & Textiles",
                "createdDate": "2020-05-27T19:20:51.249+0000"
              },
              {
                "id": "a53e602f-2ecf-4d10-a14c-4aeffc33ed35",
                "regFileNumber": "224/cpl -5/2020/ni.se",
                "listFileNumber": "string",
                "type": "ORDINANCE",
                "portfolioId": 12,
                "goNumber": "124342",
                "goDate": "2020-05-17T18:30:00.000+0000",
                "gazettePublishDate": "2020-05-01T18:30:00.000+0000",
                "isDelayed": false,
                "status": "LAYING_APPROVED",
                "layingDate": null,
                "departmentFileNumber": "string",
                "numberOfDaysInSabha": 22,
                "layingProvisionInAct": "Minister for Welfare of Scheduled Castes, Scheduled Tribes and Backward Classes ,Law, Cultur",
                "title": "ORDINANCE 1",
                "typeName": "asdf",
                "actType": "STATE",
                "actName": "act NAME",
                "typeNumber": "asdf",
                "typeDate": "2020-05-01T18:30:00.000+0000",
                "typeYear": "2020-2021",
                "sectionName": "",
                "subType": "NO_SUBTYPE",
                "ministerDepartmentName": "Industries (including Industrial Co-operatives) Commerce",
                "createdDate": "2020-05-27T19:20:53.548+0000"
              }
            ],
            "portfolioName": "Minister for Industries, Commerce, Sports and Youth Affairs"
          }
        ]
      },
      "2": {
        "id": "143ba538-ce42-4ac1-aaa9-e2347a84b3a5",
        "assemblyId": 1,
        "sessionId": 3,
        "fileId": null,
        "fileNumber": null,
        "allotmentDateId": null,
        "layingDate": "2020-08-15",
        "status": "SUBMITTED",
        "currentVersion": null,
        "documentsByPortfolioDtos": [
          {
            "portfolio": 8,
            "type": "ORDINANCE",
            "minister": "Shri. Pinarayi Vijayan",
            "documentMetaDatas": [
              {
                "id": "3aab00f5-38f9-42a3-927a-d945044621b8",
                "regFileNumber": "222/cpl -5/2020/ni.se",
                "listFileNumber": "string",
                "type": "ORDINANCE",
                "portfolioId": 8,
                "goNumber": "124342",
                "goDate": "2020-05-17T18:30:00.000+0000",
                "gazettePublishDate": "2020-05-01T18:30:00.000+0000",
                "isDelayed": false,
                "status": "LAYING_APPROVED",
                "layingDate": null,
                "departmentFileNumber": "string",
                "numberOfDaysInSabha": 22,
                "layingProvisionInAct": "Minister for Welfare of Scheduled Castes, Scheduled Tribes and Backward Classes ,Law, Cultur",
                "title": "ORDINANCE 6",
                "typeName": "asdf",
                "actType": "STATE",
                "actName": "act NAME",
                "typeNumber": "asdf",
                "typeDate": "2020-05-01T18:30:00.000+0000",
                "typeYear": "2020-2021",
                "sectionName": "",
                "subType": "NO_SUBTYPE",
                "ministerDepartmentName": "General Administration",
                "createdDate": "2020-05-27T19:20:43.068+0000"
              },
              {
                "id": "b821fd3b-8878-4bac-90f1-181a0feac34a",
                "regFileNumber": "222/cpl -5/2020/ni.se",
                "listFileNumber": "string",
                "type": "ORDINANCE",
                "portfolioId": 8,
                "goNumber": "124342",
                "goDate": "2020-05-17T18:30:00.000+0000",
                "gazettePublishDate": "2020-05-01T18:30:00.000+0000",
                "isDelayed": false,
                "status": "LAYING_APPROVED",
                "layingDate": null,
                "departmentFileNumber": "string",
                "numberOfDaysInSabha": 22,
                "layingProvisionInAct": "Minister for Welfare of Scheduled Castes, Scheduled Tribes and Backward Classes ,Law, Cultur",
                "title": "ORDINANCE 5",
                "typeName": "asdf",
                "actType": "STATE",
                "actName": "act NAME",
                "typeNumber": "asdf",
                "typeDate": "2020-05-01T18:30:00.000+0000",
                "typeYear": "2020-2021",
                "sectionName": "",
                "subType": "NO_SUBTYPE",
                "ministerDepartmentName": "General Administration",
                "createdDate": "2020-05-27T19:20:44.981+0000"
              }
            ],
            "portfolioName": "Chief Minister"
          },
          {
            "portfolio": 12,
            "type": "ORDINANCE",
            "minister": "Shri  E. P. Jayarajan",
            "documentMetaDatas": [
              {
                "id": "7f02efe1-23c1-4c03-a2dc-ddb92ddfcaa8",
                "regFileNumber": "224/cpl -5/2020/ni.se",
                "listFileNumber": "string",
                "type": "ORDINANCE",
                "portfolioId": 12,
                "goNumber": "124342",
                "goDate": "2020-05-17T18:30:00.000+0000",
                "gazettePublishDate": "2020-05-01T18:30:00.000+0000",
                "isDelayed": false,
                "status": "LAYING_APPROVED",
                "layingDate": null,
                "departmentFileNumber": "string",
                "numberOfDaysInSabha": 22,
                "layingProvisionInAct": "Minister for Welfare of Scheduled Castes, Scheduled Tribes and Backward Classes ,Law, Cultur",
                "title": "ORDINANCE 2",
                "typeName": "asdf",
                "actType": "STATE",
                "actName": "act NAME",
                "typeNumber": "asdf",
                "typeDate": "2020-05-01T18:30:00.000+0000",
                "typeYear": "2020-2021",
                "sectionName": "",
                "subType": "NO_SUBTYPE",
                "ministerDepartmentName": "Handlooms & Textiles",
                "createdDate": "2020-05-27T19:20:51.249+0000"
              },
              {
                "id": "a53e602f-2ecf-4d10-a14c-4aeffc33ed35",
                "regFileNumber": "224/cpl -5/2020/ni.se",
                "listFileNumber": "string",
                "type": "ORDINANCE",
                "portfolioId": 12,
                "goNumber": "124342",
                "goDate": "2020-05-17T18:30:00.000+0000",
                "gazettePublishDate": "2020-05-01T18:30:00.000+0000",
                "isDelayed": false,
                "status": "LAYING_APPROVED",
                "layingDate": null,
                "departmentFileNumber": "string",
                "numberOfDaysInSabha": 22,
                "layingProvisionInAct": "Minister for Welfare of Scheduled Castes, Scheduled Tribes and Backward Classes ,Law, Cultur",
                "title": "ORDINANCE 1",
                "typeName": "asdf",
                "actType": "STATE",
                "actName": "act NAME",
                "typeNumber": "asdf",
                "typeDate": "2020-05-01T18:30:00.000+0000",
                "typeYear": "2020-2021",
                "sectionName": "",
                "subType": "NO_SUBTYPE",
                "ministerDepartmentName": "Industries (including Industrial Co-operatives) Commerce",
                "createdDate": "2020-05-27T19:20:53.548+0000"
              }
            ],
            "portfolioName": "Minister for Industries, Commerce, Sports and Youth Affairs"
          }
        ]
      }
    }
  }
