const HOST_SERVER_1 = "http://192.168.204.243";
const HOST_SERVER_2 = "http://192.168.204.246";
const HOST_SERVER_3 = "http://192.168.204.250";
const HOST_SERVER_4 = "http://localhost";

export const environment = {
  chat_api_url: HOST_SERVER_3 + ":8083",
  auth_api_url: HOST_SERVER_1 + ":8090/kla/service/identity",
  login_api_url: HOST_SERVER_1 + ":8079/kla/service",
  user_mgmnt_api_url: HOST_SERVER_1 + ":8082/kla/service",
  calendar_api_url: HOST_SERVER_1 + ":8085/kla/service/v1/cos",
  document_api_url: HOST_SERVER_2 + ":8086/kla/service/v1/display",
  document_socket_api_url: HOST_SERVER_2 + ":8086",
  aod_api_url: HOST_SERVER_1 + ":7777/kla/service/v1/",
  lob_api_url: HOST_SERVER_1 + ":8084/kla/service/LobAgenda",
  business_controller_api_url: HOST_SERVER_1 + ":8084/kla/service/runningNote",
  departmentmangement_api_url: HOST_SERVER_1 + ":8089/kla/service/v1/departmentMangement",
  fileupload_url: HOST_SERVER_2 + ":8088/file",
  //user_menu_url: HOST_SERVER + ":8091/kla/service/menu",
  seat_management_url: HOST_SERVER_1 + ":8080/kla/service/seatManagement",
  vote_url: HOST_SERVER_3 + ":8092",
  lob_businesses_mock_url: HOST_SERVER_1 + ":8084/kla/service/mock/business",
  running_note_api_url: HOST_SERVER_1 + ":8084/kla/service/runningNote",
  flow_paper_api: HOST_SERVER_2 + "/kla-app/flowpaper-comm/simple_document.php?subfolder=&doc=",
  question_api_url: HOST_SERVER_1 + ":7777/kla/service/v1/",
  question_wrkflw_api_url: HOST_SERVER_1 + ":9000/kla/workflow/service/v1/",
  rules_direction_api_url: HOST_SERVER_1 + ":8089/kla/service/v1/",
  portfolio_mock_api_url: HOST_SERVER_1 + ":7777/",
  notice_processing_api: HOST_SERVER_1 + ':8030/kla/service/notice/',
  cpl_api_url: HOST_SERVER_1,
  //fileflow_api_url: HOST_SERVER,
  cpl_section_id: 8,
  fingerprintauth: HOST_SERVER_4 + ":8080/kla/service/v1/client-start-up/",
  get_system_ip: HOST_SERVER_4 + ":8080/kla/service/v1/client-start-up/getSpeakerIp",
  workflow_api: HOST_SERVER_1 + ':9000/kla/workflow/service/v1',
  file_flow_api: HOST_SERVER_1 + ':8078/kla/service/v1/files/',
  bullettin_list_api: HOST_SERVER_1 + ':8078/kla/service/v1/bulletin/',
  correspondence_api: HOST_SERVER_1 + ':8066/kla/service/v1/correspondence',
  production: true,
  rbs_api_url: HOST_SERVER_1 + ":8082/kla/service/rbs/",
  report_api_url: HOST_SERVER_1 + ':8095',
  bulletin_api: HOST_SERVER_1 + ':8078/kla/service/v1/bulletin/',
  user_management_api: HOST_SERVER_1 + ':8082/',
  lob_ProceedingReporter_api_uri: HOST_SERVER_1 + ":8084/kla/service/v1/proceeding",
};
