export interface electedMemeber {
    action: string,
    applicationRole :[],
    details:details;
    userId: number,
    userName: string,
    userType: string,
    validated:boolean
    electionDetails :electionDetails[],
    terms : terms[],
    roles: any[],
    postions : postions[]
    rbsRole: any
}
export interface details {
    id: number,
    fullName: string,
    malayalamFullName: string,
    firstName: string,
    lastName: string,
    email: string,
    mobileNumber: string,
    profilePhoto: string,
    keralaConstituencyId: string,
    keralaConstituencyName: string,
    keralaPolicticalPartyid:number,
    gender: string,
    nationality: string,
    presetincome: string,
    dateOfBirth: string,
    placeOfBirth: string,
    languageKnown: [],
    hobbies: [],
    profession: [],
    recreation: [],
    literary: [],
    briefHistory: string,
    address : address[],
    relatedPersons : relatedPersons[],
    assests : assests[],
    contactInfo:contactInfo[],
    keralaConstituencyCode: string,
    keralaConstiturencyName: string,
    partyNameMalayalam: string,
    constituencyNameMalayalam: string,
    keralaPolicticalPartyName: string,
    keralaPartyFrontName:string,
    keralaPartyNameInMalayalam:string,
    sectionId: number,
    sectionName:string,
    designationId: number,
    designationName: string,
    memberDesignationName:string,
    married: boolean,
    traveledAbroad: boolean,
    password: string,
    terms : terms[],
    userId: any,
    userName: string,
    klaUser: boolean,
    memberGroup: string,
    keralaPartyFrontId: any,
    memberDesignationId: any,
    portfolioId: any,
    deceased: any,
    deceasedDate: any,
    deceasedReason: any,
  }
export interface address {
        id: number,
        line1: string,
        line2: string,
        line3: string,
        village: string,
        taluk: string,
        districtId: number,
        district: string,
        stateId: number,
        state: string,
        countryId: number,
        country: string,
        pinCode: string,
        talukId: number,
        nearestRailWay: string,
        distanceRail: string,
        shortdistResToTvm: string,
        treasuryForTA: string,
        classITractD: string,
        classIItractD: string,
        taLocation: boolean,
        addressTypeName: string,
        addressTypeCode: string
}
export interface relatedPersons{
    id: number,
    firstName: string,
    lastName: string,
    displayName: string,
    delete: boolean,
    nominee: boolean,
    relationCode: string,
    relationName: string,
    address: address[],
    contactInfo: contactInfo[],
    klaUser: string,
    userRelatedPersonId:number
}
export interface assests
{
    id: number,
    ownedBy: string,
    acquisitionDate: string,
    acquisitionType: string,
    type: string,
    taluk: string,
    talukId: number,
    district: string,
    stateId: number,
    state: string,
    village: string,
    presentValue: number,
    acquisitionDetails: string,
    annualIncomeFromProperty: number,
    delete: boolean,
    userAssetId: number,
    klaUser: false,
    districtId: number
}

export interface contactInfo  {
    id: number,
    code: string,
    name: string,
    contactTypeCode: string,
    contactTypeName: string,
    userContactId: number,
    klaUser: boolean,
    delete: boolean
  }
export interface terms{
    id: number,
    assemblyId: number,
    assemblyValue: string,
    startDate: string,
    endDate: string,
    memberName: string,
    memberNameMalayalam:string,
    endType: string,
    description:string,
    status: string,
    userId: number
}  
export interface electionDetails{
    assemblyId: 0,
    assemblyValue: 0,
    byElection: boolean,
    constituencyId: 0,
    constituencyName: string,
    electionDate: string,
    electionId: 0,
    formId: string,
    id: 0,
    oathForm: string,
    oathStatus: string,
    partyId: 0,
    partyName: string,
    remark: string,
    resulDate: string,
    status: string,
    userId: 0
}

export interface terms{
      assemblyId: number,
      description: string,
      electionId: 0,
      endDate: string,
      assemblyValue: string,
      endType: string,
      id: number,
      memberName: string,
      memberNameMalayalam: string,
      startDate: string,
      status: string,
      userId: number
}

export interface postions{
    assemblyId: number,
    assemblyValue: number,
    designationId: number,
    designation:string,
    endDate: string,
    id: number,
    memberGroup: string,
    memberGroupDisplay : string,
    partyFrontId: number,
    partyFront:string,
    portfolioId: number,
    portfolio : string,
    startDate: string,
    status: string,
    userId: number
}